name = "spinogambinogame-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambinogame.com"
HMAC_KEY = "04c8c10952bfa8ed5f0ebb88aa48e9b3f9ff2539d85e16dd971ae35421a0a775"
COOKIE_NAME = "mg9"
PLAY_PATH = "begin"
BUTTON_ID = "p91bf40fc36ce07a45ae5b1700f5d5349"
GATE_SALT = "b3e694dfb5b1bde4"
